from app.prompts.templates import (
    CHAT_CONTEXT_INJECTION,
    MASTER_SYSTEM_PROMPT,
    NOTIFICATION_TRIGGER_PROMPT,
    PATTERN_INTELLIGENCE_PROMPT,
    REVISION_QUEUE_PROMPT,
    SUBMISSION_ANALYSIS_PROMPT,
)

__all__ = [
    "MASTER_SYSTEM_PROMPT",
    "SUBMISSION_ANALYSIS_PROMPT",
    "PATTERN_INTELLIGENCE_PROMPT",
    "REVISION_QUEUE_PROMPT",
    "NOTIFICATION_TRIGGER_PROMPT",
    "CHAT_CONTEXT_INJECTION",
]
